function Test-InventorySessionIdUnassigned {
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute(
        'PSUseShouldProcessForStateChangingFunctions',
        '',
        Justification = 'Checks an in-memory value without changing system state.'
    )]
    param(
        [AllowNull()][string]$SessionId
    )

    $normalized = Get-SafeString $SessionId
    return ($null -eq $normalized) -or ($normalized -eq 'SES-UNASSIGNED')
}

function Get-InventoryAutoGeneratedSessionId {
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute(
        'PSUseShouldProcessForStateChangingFunctions',
        '',
        Justification = 'Generates a value from the current time without changing system state.'
    )]
    param(
        [datetimeoffset]$Now = [datetimeoffset]::Now
    )

    # Timestamp-based, same convention as CollectionId/AssetId elsewhere in
    # this codebase (unique per launcher run, no PII embedded — Técnico's
    # name is tracked separately as CollectionSession.Technician, not folded
    # into the identifier itself).
    return 'SES-{0}' -f $Now.ToString('yyyyMMdd-HHmmss')
}

function New-InventoryCollectionSession {
    [CmdletBinding()]
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute(
        'PSUseShouldProcessForStateChangingFunctions',
        '',
        Justification = 'Creates and returns an in-memory session value without changing system state.'
    )]
    param(
        [AllowNull()][string]$SessionId,
        [AllowNull()][string]$OrganizationId,
        [string]$ProfileId = 'basic-inventory',
        [AllowNull()][string]$Technician,
        [datetimeoffset]$StartedAt = [datetimeoffset]::Now,
        [int]$EquipmentCount = 0,
        [int]$PendingCount = 0
    )

    $normalizedSessionId = Get-SafeString $SessionId
    $isUnassigned = Test-InventorySessionIdUnassigned -SessionId $SessionId

    if ($isUnassigned) {
        Write-Warning ('Ejecutando sin sesión de recolección asignada — esta captura debe ' +
            'revisarse antes de la consolidación institucional.')
    }

    return [ordered]@{
        SessionId = if ($null -ne $normalizedSessionId) { $normalizedSessionId } else { 'SES-UNASSIGNED' }
        OrganizationId = $OrganizationId
        ProfileId = $ProfileId
        Technician = $Technician
        StartedAt = $StartedAt.ToString('o')
        EndedAt = $null
        EquipmentCount = $EquipmentCount
        PendingCount = $PendingCount
        Status = if ($isUnassigned) { 'Unassigned' } else { 'Active' }
    }
}
