$ErrorActionPreference = "Stop"

try {
    $basePath = Split-Path -Parent $MyInvocation.MyCommand.Path
    $collector = Join-Path $basePath "Collector_Hardware_Inventory.ps1"
    $healthCollector = Join-Path $basePath "Collector_Windows_HealthCheck.ps1"
    $storageCollector = Join-Path $basePath "Collector_Storage_Diagnostic.ps1"
    $configPath = Join-Path $basePath "config.json"

    if (-not (Test-Path -LiteralPath $collector)) {
        throw "No se encontró el recolector principal: $collector"
    }
    if (-not (Test-Path -LiteralPath $healthCollector)) {
        throw "No se encontró el diagnóstico de salud: $healthCollector"
    }
    if (-not (Test-Path -LiteralPath $storageCollector)) {
        throw "No se encontró el diagnóstico de almacenamiento: $storageCollector"
    }

    if (-not (Test-Path -LiteralPath $configPath)) {
        throw "No se encontró el archivo de configuración: $configPath"
    }

    . (Join-Path $basePath "Modules\Common.ps1")
    . (Join-Path $basePath "Modules\New-InventoryCollectionSession.ps1")
    . (Join-Path $basePath "Modules\InventoryOrganizationPackage.ps1")
    . (Join-Path $basePath "Modules\New-InventoryManualCapture.ps1")
    . (Join-Path $basePath "Modules\New-InventoryConsolidatedWorkbook.ps1")

    $config = Get-Content -LiteralPath $configPath -Raw -Encoding UTF8 | ConvertFrom-Json

    # Resolve manual fields from the active organization's profile, if one
    # is configured; otherwise config.json's flat ManualFields list is used
    # as-is (unchanged backward-compatible behavior).
    $organizationPackagesBasePath = ".\Config\Organizations"
    if ($null -ne $config.OrganizationPackages -and
        $config.OrganizationPackages.PSObject.Properties.Name -contains "BasePath") {
        $organizationPackagesBasePath = $config.OrganizationPackages.BasePath
    }
    $resolvedOrganizationPackagesBasePath = Join-Path $basePath ($organizationPackagesBasePath -replace '^[.][\\/]', '')

    $sessionParameters = @{
        SessionId = "SES-UNASSIGNED"
        OrganizationId = $null
        ProfileId = "basic-inventory"
        Technician = $null
    }

    if ($null -ne $config.CollectionSession) {
        foreach ($propertyName in @("SessionId", "OrganizationId", "ProfileId", "Technician")) {
            if ($config.CollectionSession.PSObject.Properties.Name -contains $propertyName) {
                $sessionParameters[$propertyName] = $config.CollectionSession.$propertyName
            }
        }
    }

    # config.json not pinning an OrganizationId used to mean "no catalog,
    # free text only" even with a real organization package already sitting
    # on disk — auto-detect it instead of requiring a manual edit before the
    # catalog the technician just copied over would ever be used. An
    # explicit OrganizationId in config.json always wins over auto-detection.
    if ($null -eq (Get-SafeString $sessionParameters.OrganizationId)) {
        $autoDetectedOrganizationId = Get-InventoryAutoDetectedOrganizationId -BasePath $resolvedOrganizationPackagesBasePath
        if ($null -ne $autoDetectedOrganizationId) {
            $sessionParameters.OrganizationId = $autoDetectedOrganizationId
        }
    }

    # Bugfix: entering a Técnico through the visit-context prompt below used
    # to leave the administration "Nuevos equipos" table showing
    # SES-UNASSIGNED anyway — SessionId and Technician were resolved
    # completely independently, and nothing ever generated a real session id
    # just from answering who's doing the visit. Auto-generate one, unique
    # per launcher run, whenever config.json does not pin an explicit one; an
    # explicit SessionId in config.json always wins over auto-generation
    # (same pattern as OrganizationId auto-detection above).
    if (Test-InventorySessionIdUnassigned -SessionId $sessionParameters.SessionId) {
        $sessionParameters.SessionId = Get-InventoryAutoGeneratedSessionId
    }

    $collectionSession = New-InventoryCollectionSession @sessionParameters -WarningAction Continue

    $manualFieldKeys = Get-InventoryProfileManualFields `
        -BasePath $resolvedOrganizationPackagesBasePath `
        -OrganizationId $collectionSession.OrganizationId `
        -ProfileId $collectionSession.ProfileId `
        -FallbackFields @($config.ManualFields)

    # doc07-Catalog-System.md: when the active organization has an
    # organization-unit catalog, the technician picks assignment.organizationUnitId
    # from it during capture instead of typing free text.
    $organizationUnits = Get-InventoryOrganizationUnitCatalog `
        -BasePath $resolvedOrganizationPackagesBasePath `
        -OrganizationId $collectionSession.OrganizationId

    # doc07-Catalog-System.md flat/independent mode: some institutions'
    # Dirección and Departamento have no reliable parent-child relationship
    # (rows in each list don't line up), so a second, independent
    # catalogs/departments.json can be shipped alongside organization-units.json.
    # When present, Read-InventoryManualCapture picks assignment.departmentUnitId
    # from this whole catalog directly instead of cascading from $organizationUnits.
    $departmentUnits = Get-InventoryDepartmentUnitCatalog `
        -BasePath $resolvedOrganizationPackagesBasePath `
        -OrganizationId $collectionSession.OrganizationId

    # "Labels legibles" task: the technician sees "Dirección" / "Número
    # patrimonial" / etc. instead of the raw dotted field keys. Only the
    # organization's own overrides go into $fieldLabels here — the hardcoded
    # defaults (Get-InventoryDefaultFieldLabel) are resolved lazily by
    # Get-InventoryFieldLabel wherever a label is actually needed, so they
    # never need duplicating in this launcher.
    $customFieldDefinitions = Get-InventoryCustomFieldDefinitions `
        -BasePath $resolvedOrganizationPackagesBasePath `
        -OrganizationId $collectionSession.OrganizationId

    $fieldLabels = @{}
    foreach ($fieldDefinition in @($customFieldDefinitions)) {
        if ($null -eq $fieldDefinition) { continue }
        $fieldKey = Get-SafeString ([string]$fieldDefinition.key)
        $fieldLabel = Get-SafeString ([string]$fieldDefinition.label)
        if ($null -ne $fieldKey -and $null -ne $fieldLabel) {
            $fieldLabels[$fieldKey] = $fieldLabel
        }
    }

    # doc07-Catalog-System.md "Reutilización durante visita": El técnico
    # selecciona un contexto (Técnico/Dirección/Departamento). Los valores se
    # heredan hasta que se cambien, evitando capturar el mismo departamento
    # en cada equipo de una misma visita. Resolved once here, and again on
    # demand from the menu (option 9) — never per collection.
    function Read-InventoryVisitContext {
        param(
            [AllowNull()][string]$CurrentTechnician,
            [AllowNull()][object[]]$OrganizationUnits = @(),
            [AllowNull()][object[]]$DepartmentUnits = @(),
            [AllowNull()][hashtable]$FieldLabels = @{}
        )

        Write-Host ""
        Write-Host "--- Contexto de esta visita ---" -ForegroundColor Cyan

        $technicianAnswer = Get-SafeString (Read-Host "Técnico responsable de esta visita (Enter para mantener '$CurrentTechnician')")
        $resolvedTechnician = if ($null -ne $technicianAnswer) { $technicianAnswer } else { $CurrentTechnician }

        $presetValues = @{}
        $hasOrganizationUnits = @($OrganizationUnits).Count -gt 0
        $hasDepartmentUnits = @($DepartmentUnits).Count -gt 0

        $directionLabel = Get-InventoryFieldLabel -Key 'assignment.organizationUnitId' -FieldLabels $FieldLabels
        $departmentLabel = Get-InventoryFieldLabel -Key 'assignment.departmentUnitId' -FieldLabels $FieldLabels

        $directionSelection = $null
        if ($hasOrganizationUnits) {
            # ConvertTo-InventoryOrganizationUnitMenu renders the FULL tree of
            # whatever -Units it gets, children included — passing the whole
            # catalog here would show every Departamento nested inside this
            # "Dirección" prompt too, letting the technician pick a leaf
            # (department-level) entry by mistake at the direction step. Only
            # root-level units (parentId = null) belong in this first prompt;
            # the cascade below already narrows to the selected direction's
            # own children for the Departamento step.
            $rootOrganizationUnits = Get-InventoryOrganizationUnitChildren -Units $OrganizationUnits -ParentId $null
            $directionSelection = Read-InventoryOrganizationUnitSelection -Units $rootOrganizationUnits -Label $directionLabel
            if ($null -ne $directionSelection) {
                $presetValues['assignment.organizationUnitId'] = $directionSelection.Name
            }
        }

        if ($hasDepartmentUnits) {
            # Flat/independent mode: Departamento is always offered on its
            # own, regardless of whether Dirección was picked above — same
            # priority Read-InventoryManualCapture itself gives
            # -DepartmentUnits over the cascade.
            $departmentSelection = Read-InventoryOrganizationUnitSelection -Units $DepartmentUnits -Label $departmentLabel
            if ($null -ne $departmentSelection) {
                $presetValues['assignment.departmentUnitId'] = $departmentSelection.Name
            }
        }
        elseif ($null -ne $directionSelection) {
            $childUnits = Get-InventoryOrganizationUnitChildren -Units $OrganizationUnits -ParentId $directionSelection.Id
            if (@($childUnits).Count -gt 0) {
                $departmentSelection = Read-InventoryOrganizationUnitSelection -Units $childUnits -Label $departmentLabel
                if ($null -ne $departmentSelection) {
                    $presetValues['assignment.departmentUnitId'] = $departmentSelection.Name
                }
                else {
                    # Dirección has children but the technician skipped
                    # Departamento (Enter): un-preset Dirección too.
                    # Presetting only Dirección would strand the per-machine
                    # cascade — Read-InventoryManualCapture needs the picked
                    # Dirección's real Id to filter children, and a preset
                    # bypass only ever stores its Name. Both fields fall
                    # through to the normal per-machine flow instead, where
                    # the cascade still works correctly.
                    $presetValues.Remove('assignment.organizationUnitId')
                }
            }
        }

        return [ordered]@{
            Technician = $resolvedTechnician
            PresetValues = $presetValues
        }
    }

    $visitContext = Read-InventoryVisitContext -CurrentTechnician $collectionSession.Technician `
        -OrganizationUnits $organizationUnits -DepartmentUnits $departmentUnits -FieldLabels $fieldLabels
    $visitTechnician = $visitContext.Technician
    $visitPresetValues = $visitContext.PresetValues
    Update-InventoryConfigTechnician -ConfigPath $configPath -Technician $visitTechnician

    $collectionArguments = @{
        SessionId = $collectionSession.SessionId
        Technician = $visitTechnician
        ManualFieldKeys = $manualFieldKeys
        OrganizationUnits = $organizationUnits
        DepartmentUnits = $departmentUnits
        PresetManualFieldValues = $visitPresetValues
        FieldLabels = $fieldLabels
    }
    # Set separately (not inside the @{...} literal above): its real value is
    # only known once Read-InventoryPriorCollectionCheck runs, right before
    # each collection dispatch below — same "set after the fact" pattern menu
    # option 9 already uses for PresetManualFieldValues.
    $collectionArguments.DefaultManualFieldValues = @{}

    # "Ya se recolectó este equipo" warning + host-history defaults: before
    # dispatching Collector_Hardware_Inventory.ps1, check whether this host
    # already has a prior *-record.json under Output\<Hostname>\
    # (Resolve-InventoryHostOutputDirectory / Get-InventoryLatestHostRecord). If
    # one exists, warn the technician with that collection's date/time and
    # let them abort instead of silently re-collecting. Confirming (or no
    # prior record at all) reuses Nombre/Dirección/Departamento from that
    # record as visible, editable defaults (-DefaultManualFieldValues) —
    # distinct from -PresetManualFieldValues above, which skips the prompt
    # silently instead of just pre-filling it. A visit-level preset for the
    # same key always wins over old host history (Get-InventoryHostHistoryDefaultValues
    # enforces that precedence), so $PresetValues is forwarded through.
    function Read-InventoryPriorCollectionCheck {
        param(
            [Parameter(Mandatory)][string]$Hostname,
            [Parameter(Mandatory)][string]$OutputDirectory,
            [AllowNull()][hashtable]$PresetValues = @{}
        )

        # Resolve-InventoryHostOutputDirectory (read-only lookup), not
        # Get-InventoryHostOutputDirectory — this must find a folder that
        # already carries a display-name suffix
        # (Collector_Hardware_Inventory.ps1), and must never mint/create a
        # new folder name of its own. HostOutputDirectory below is
        # Mandatory, so a $null result (no prior folder at all — first-ever
        # collection for this machine) is short-circuited here instead of
        # being passed through.
        $hostOutputDir = Resolve-InventoryHostOutputDirectory -BaseOutputDirectory $OutputDirectory -Hostname $Hostname
        $priorRecord = if ($null -ne $hostOutputDir) { Get-InventoryLatestHostRecord -HostOutputDirectory $hostOutputDir } else { $null }

        if ($null -eq $priorRecord) {
            return [ordered]@{ Proceed = $true; DefaultValues = @{} }
        }

        $priorCollectedAt = Get-InventoryWorkbookCollectedAtDateTime -CollectedAt $priorRecord.CollectedAt
        $priorCollectedAtText = if ($null -ne $priorCollectedAt) {
            $priorCollectedAt.ToString('dd/MM/yyyy HH:mm')
        }
        else {
            'una fecha desconocida'
        }

        Write-Host ""
        Write-Host "Este equipo ya tiene un inventario recolectado el $priorCollectedAtText." -ForegroundColor Yellow
        $answer = Get-SafeString (Read-Host "¿Desea continuar de todas formas? (S/N)")

        if ($null -eq $answer -or $answer -notmatch '^[sS]') {
            Write-Host "Recolección cancelada." -ForegroundColor Yellow
            return [ordered]@{ Proceed = $false; DefaultValues = @{} }
        }

        $defaultValues = Get-InventoryHostHistoryDefaultValues -PriorRecord $priorRecord -PresetValues $PresetValues
        return [ordered]@{ Proceed = $true; DefaultValues = $defaultValues }
    }

    function Wait-MenuInput {
        Write-Host ""
        [void](Read-Host "Presione Enter para continuar")
    }

    $option = ""

    do {
        Clear-Host
        Write-Host "========================================" -ForegroundColor Cyan
        Write-Host "     RECOLECTOR DE INVENTARIO TI" -ForegroundColor Cyan
        Write-Host "========================================" -ForegroundColor Cyan
        Write-Host ""
        Write-Host "Equipo: $env:COMPUTERNAME"
        Write-Host "Usuario: $env:USERNAME"
        Write-Host ""
        Write-Host "1. Generar inventario completo"
        Write-Host "2. Generar inventario rápido"
        Write-Host "3. Ejecutar diagnóstico de salud"
        Write-Host "4. Abrir carpeta de resultados"
        Write-Host "5. Abrir último reporte de inventario"
        Write-Host "6. Abrir último diagnóstico de salud"
        Write-Host "7. Abrir carpeta de logs"
        Write-Host "8. Salir"
        Write-Host "9. Cambiar contexto de esta visita (Dirección/Departamento/Técnico)"
        Write-Host "10. Ejecutar diagnóstico de almacenamiento"
        Write-Host ""

        $option = Read-Host "Seleccione una opción"

        switch ($option) {
            "1" {
                $config = Get-Content -LiteralPath $configPath -Raw -Encoding UTF8 | ConvertFrom-Json
                $relativeOutput = $config.OutputDirectory -replace '^[.][\\/]', ''
                $output = Join-Path $basePath $relativeOutput
                $hostname = $env:COMPUTERNAME -replace '[^a-zA-Z0-9_-]', '_'

                $priorCollectionCheck = Read-InventoryPriorCollectionCheck -Hostname $hostname `
                    -OutputDirectory $output -PresetValues $visitPresetValues

                if ($priorCollectionCheck.Proceed) {
                    $collectionArguments.DefaultManualFieldValues = $priorCollectionCheck.DefaultValues
                    $result = & $collector -Mode Full @collectionArguments

                    if ($null -ne $result -and $result.Success) {
                        if (Test-Path -LiteralPath $result.HtmlPath) {
                            Start-Process -FilePath $result.HtmlPath
                        }
                    }
                    else {
                        Write-Host "El inventario no pudo completarse." -ForegroundColor Red
                    }
                }

                Wait-MenuInput
            }

            "2" {
                $config = Get-Content -LiteralPath $configPath -Raw -Encoding UTF8 | ConvertFrom-Json
                $relativeOutput = $config.OutputDirectory -replace '^[.][\\/]', ''
                $output = Join-Path $basePath $relativeOutput
                $hostname = $env:COMPUTERNAME -replace '[^a-zA-Z0-9_-]', '_'

                $priorCollectionCheck = Read-InventoryPriorCollectionCheck -Hostname $hostname `
                    -OutputDirectory $output -PresetValues $visitPresetValues

                if ($priorCollectionCheck.Proceed) {
                    $collectionArguments.DefaultManualFieldValues = $priorCollectionCheck.DefaultValues
                    $result = & $collector -Mode Quick @collectionArguments

                    if ($null -ne $result -and $result.Success) {
                        if (Test-Path -LiteralPath $result.HtmlPath) {
                            Start-Process -FilePath $result.HtmlPath
                        }
                    }
                    else {
                        Write-Host "El inventario no pudo completarse." -ForegroundColor Red
                    }
                }

                Wait-MenuInput
            }

            "3" {
                $result = & $healthCollector -Mode Diagnostic
                if ($null -ne $result -and $result.Success) {
                    Write-Host ""
                    Write-Host "Diagnóstico finalizado correctamente." -ForegroundColor Green
                    if (-not [string]::IsNullOrWhiteSpace($result.JsonPath)) { Write-Host "JSON: $($result.JsonPath)" }
                    if (-not [string]::IsNullOrWhiteSpace($result.LogPath)) { Write-Host "Log:  $($result.LogPath)" }
                    if (-not [string]::IsNullOrWhiteSpace($result.HtmlPath) -and (Test-Path -LiteralPath $result.HtmlPath)) {
                        Write-Host "HTML: $($result.HtmlPath)"
                        Start-Process -FilePath $result.HtmlPath
                    }
                    else { Write-Host "El reporte HTML está deshabilitado o no fue generado." -ForegroundColor Yellow }
                }
                else { Write-Host "El diagnóstico de salud no pudo completarse." -ForegroundColor Red }
                Wait-MenuInput
            }
            "4" {
                $config = Get-Content -LiteralPath $configPath -Raw -Encoding UTF8 | ConvertFrom-Json
                $relativeOutput = $config.OutputDirectory -replace '^[.][\\/]', ''
                $output = Join-Path $basePath $relativeOutput

                New-Item -ItemType Directory -Force -Path $output | Out-Null
                Start-Process -FilePath "explorer.exe" -ArgumentList $output
            }

            "5" {
                $config = Get-Content -LiteralPath $configPath -Raw -Encoding UTF8 | ConvertFrom-Json
                $relativeOutput = $config.OutputDirectory -replace '^[.][\\/]', ''
                $output = Join-Path $basePath $relativeOutput

                New-Item -ItemType Directory -Force -Path $output | Out-Null

                $last = Get-ChildItem -LiteralPath $output -Filter "*.html" -Recurse -ErrorAction SilentlyContinue |
                    Where-Object { $_.Name -notlike "*-health.html" } |
                    Sort-Object LastWriteTime -Descending |
                    Select-Object -First 1

                if ($null -ne $last) {
                    Start-Process -FilePath $last.FullName
                }
                else {
                    Write-Host "Todavía no existe un reporte HTML." -ForegroundColor Yellow
                    Wait-MenuInput
                }
            }

            "6" {
                $config = Get-Content -LiteralPath $configPath -Raw -Encoding UTF8 | ConvertFrom-Json
                $output = Join-Path $basePath ($config.OutputDirectory -replace '^[.][\\/]', '')
                $last = Get-ChildItem -LiteralPath $output -Filter "*-health.html" -Recurse -ErrorAction SilentlyContinue | Sort-Object LastWriteTime -Descending | Select-Object -First 1
                if ($null -ne $last) { Start-Process -FilePath $last.FullName }
                else { Write-Host "Todavía no existe un diagnóstico de salud." -ForegroundColor Yellow; Wait-MenuInput }
            }
            "7" {
                $config = Get-Content -LiteralPath $configPath -Raw -Encoding UTF8 | ConvertFrom-Json
                $relativeLogs = $config.LogDirectory -replace '^[.][\\/]', ''
                $logs = Join-Path $basePath $relativeLogs

                New-Item -ItemType Directory -Force -Path $logs | Out-Null
                Start-Process -FilePath "explorer.exe" -ArgumentList $logs
            }

            "8" {
                Write-Host ""
                Write-Host "Cerrando el recolector..."
            }

            "9" {
                $visitContext = Read-InventoryVisitContext -CurrentTechnician $visitTechnician `
                    -OrganizationUnits $organizationUnits -DepartmentUnits $departmentUnits -FieldLabels $fieldLabels
                $visitTechnician = $visitContext.Technician
                $visitPresetValues = $visitContext.PresetValues
                Update-InventoryConfigTechnician -ConfigPath $configPath -Technician $visitTechnician
                $collectionArguments.Technician = $visitTechnician
                $collectionArguments.PresetManualFieldValues = $visitPresetValues

                Wait-MenuInput
            }

            "10" {
                $result = & $storageCollector -Mode Diagnostic
                if ($null -ne $result -and $result.Success) {
                    Write-Host ""
                    Write-Host "Diagnóstico de almacenamiento finalizado correctamente." -ForegroundColor Green
                    if (-not [string]::IsNullOrWhiteSpace($result.JsonPath)) { Write-Host "JSON: $($result.JsonPath)" }
                    if (-not [string]::IsNullOrWhiteSpace($result.LogPath)) { Write-Host "Log:  $($result.LogPath)" }
                    if (-not [string]::IsNullOrWhiteSpace($result.HtmlPath) -and (Test-Path -LiteralPath $result.HtmlPath)) {
                        Write-Host "HTML: $($result.HtmlPath)"
                        Start-Process -FilePath $result.HtmlPath
                    }
                    else { Write-Host "El reporte HTML está deshabilitado o no fue generado." -ForegroundColor Yellow }
                }
                else { Write-Host "El diagnóstico de almacenamiento no pudo completarse." -ForegroundColor Red }
                Wait-MenuInput
            }

            default {
                Write-Host "Opción no válida." -ForegroundColor Yellow
                Start-Sleep -Seconds 1
            }
        }
    }
    while ($option -ne "8")

    return
}
catch {
    Write-Host ""
    Write-Host "========================================" -ForegroundColor Red
    Write-Host " ERROR AL INICIAR EL RECOLECTOR" -ForegroundColor Red
    Write-Host "========================================" -ForegroundColor Red
    Write-Host ""
    Write-Host $_.Exception.Message -ForegroundColor Red
    Write-Host ""
    Write-Host "Archivo: $($_.InvocationInfo.ScriptName)"
    Write-Host "Línea: $($_.InvocationInfo.ScriptLineNumber)"
    Write-Host ""
    [void](Read-Host "Presione Enter para cerrar")
    return
}
