BeforeAll {
    . "$PSScriptRoot/../Modules/Common.ps1"
    . "$PSScriptRoot/../Modules/New-InventoryCollectionSession.ps1"
}

Describe 'New-InventoryCollectionSession' {
    It 'builds an active session entity with the supplied context' {
        $startedAt = [datetimeoffset]'2026-08-03T08:00:00-06:00'

        $session = New-InventoryCollectionSession `
            -SessionId 'SES-20260803-AM-RH' `
            -OrganizationId 'ORG-001' `
            -ProfileId 'basic-inventory' `
            -Technician 'Brandon' `
            -StartedAt $startedAt

        $session.SessionId | Should -Be 'SES-20260803-AM-RH'
        $session.OrganizationId | Should -Be 'ORG-001'
        $session.ProfileId | Should -Be 'basic-inventory'
        $session.Technician | Should -Be 'Brandon'
        $session.StartedAt | Should -Be $startedAt.ToString('o')
        $session.EndedAt | Should -BeNullOrEmpty
        $session.EquipmentCount | Should -Be 0
        $session.PendingCount | Should -Be 0
        $session.Status | Should -Be 'Active'
    }

    It 'defaults ProfileId to basic-inventory when not supplied' {
        $session = New-InventoryCollectionSession -SessionId 'SES-20260803-AM-RH'

        $session.ProfileId | Should -Be 'basic-inventory'
    }

    It 'marks the session Unassigned and warns when no SessionId is supplied' {
        $session = New-InventoryCollectionSession -WarningVariable warnings -WarningAction SilentlyContinue

        $session.SessionId | Should -Be 'SES-UNASSIGNED'
        $session.Status | Should -Be 'Unassigned'
        $warnings.Count | Should -BeGreaterThan 0
        [string]$warnings[0] | Should -Match 'sin sesión de recolección asignada'
    }

    It 'marks the session Unassigned and warns when SessionId is the empty string' {
        $session = New-InventoryCollectionSession -SessionId '' -WarningVariable warnings -WarningAction SilentlyContinue

        $session.SessionId | Should -Be 'SES-UNASSIGNED'
        $session.Status | Should -Be 'Unassigned'
        $warnings.Count | Should -BeGreaterThan 0
    }

    It 'marks the session Unassigned and warns when SessionId is the default literal SES-UNASSIGNED' {
        $session = New-InventoryCollectionSession -SessionId 'SES-UNASSIGNED' -WarningVariable warnings -WarningAction SilentlyContinue

        $session.SessionId | Should -Be 'SES-UNASSIGNED'
        $session.Status | Should -Be 'Unassigned'
        $warnings.Count | Should -BeGreaterThan 0
    }

    It 'does not warn when a real SessionId is supplied' {
        $session = New-InventoryCollectionSession -SessionId 'SES-20260803-AM-RH' -WarningVariable warnings -WarningAction SilentlyContinue

        $session.Status | Should -Be 'Active'
        $warnings.Count | Should -Be 0
    }
}

Describe 'Test-InventorySessionIdUnassigned' {
    It 'treats null, empty, whitespace and the literal SES-UNASSIGNED as unassigned' {
        Test-InventorySessionIdUnassigned -SessionId $null | Should -BeTrue
        Test-InventorySessionIdUnassigned -SessionId '' | Should -BeTrue
        Test-InventorySessionIdUnassigned -SessionId '   ' | Should -BeTrue
        Test-InventorySessionIdUnassigned -SessionId 'SES-UNASSIGNED' | Should -BeTrue
    }

    It 'treats any other non-empty SessionId as assigned' {
        Test-InventorySessionIdUnassigned -SessionId 'SES-20260803-AM-RH' | Should -BeFalse
    }
}

Describe 'Get-InventoryAutoGeneratedSessionId' {
    It 'generates a real, non-placeholder SessionId derived from the current time' {
        $now = [datetimeoffset]'2026-08-04T14:05:30-06:00'

        $generated = Get-InventoryAutoGeneratedSessionId -Now $now

        $generated | Should -Not -Be 'SES-UNASSIGNED'
        Test-InventorySessionIdUnassigned -SessionId $generated | Should -BeFalse
        $generated | Should -Be 'SES-20260804-140530'
    }

    It 'defaults to the current time when Now is not supplied' {
        { Get-InventoryAutoGeneratedSessionId } | Should -Not -Throw
        Test-InventorySessionIdUnassigned -SessionId (Get-InventoryAutoGeneratedSessionId) | Should -BeFalse
    }
}
